apiVersion: v1
kind: Service
metadata:
  name: tiny-crash-app
  namespace: apps
spec:
  selector:
    app: tiny-crash-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
